In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("/Users/sidhi/Desktop/job_analytics/data/job_descriptions.xlsx")

In [5]:
df.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [7]:
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [9]:
df.describe()

,Job Id,latitude,longitude,Company Size,Job Posting Date
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,1.549784e+15,1.937667e+01,1.642460e+01,7.370591e+04,4.481908e+04
std,8.948046e+14,2.354377e+01,7.063506e+01,3.530437e+04,2.111549e+02
min,1.817948e+11,-4.090060e+01,-1.751982e+02,1.264600e+04,4.445400e+04
25%,7.746128e+14,5.152100e+00,-1.518040e+01,4.312100e+04,4.463600e+04
50%,1.549470e+15,1.804250e+01,1.914510e+01,7.364100e+04,4.481900e+04
75%,2.325066e+15,3.907420e+01,4.757690e+01,1.043175e+05,4.500200e+04
max,3.099618e+15,7.170690e+01,1.780650e+02,1.348340e+05,4.518400e+04

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1048575 non-null  int64
 1   Experience        1048575 non-null  object
 2   Qualifications    1048575 non-null  object
 3   Salary Range      1048575 non-null  object
 4   location          1048575 non-null  object
 5   Country           1048575 non-null  object
 6   latitude          1048575 non-null  float64
 7   longitude         1048575 non-null  float64
 8   Work Type         1048575 non-null  object
 9   Company Size      1048575 non-null  int64
 10  Job Posting Date  1048575 non-null  int64
 11  Preference        1048575 non-null  object
 12  Contact Person    1048575 non-null  object
 13  Contact           1048575 non-null  object
 14  Job Title         1048575 non-null  object
 15  Role              1048575 non-null  object
 16  Job Portal        1048575 non-null  object
 17  Job Description   1048575 non-null  object
 18  Benefits          1048575 non-null  object
 19  skills            1048575 non-null  object
 20  Responsibilities  1048575 non-null  object
 21  Company           1048575 non-null  object
 22  Company Profile   1044968 non-null  object
dtypes: float64(2), int64(3), object(18)
memory usage: 184.0+ MB

In [11]:
df.shape

(1048575, 23)

In [12]:
df.Qualifications

0          M.Tech
1             BCA
2             PhD
3             PhD
4             MBA
            ...
1048570     B.Com
1048571       MCA
1048572       BBA
1048573       MCA
1048574     M.Com
Name: Qualifications, Length: 1048575, dtype: object

In [13]:
df.columns = df.columns.str.replace(" ","_")

In [14]:
df.columns

Index(['Job_Id', 'Experience', 'Qualifications', 'Salary_Range', 'location',
       'Country', 'latitude', 'longitude', 'Work_Type', 'Company_Size',
       'Job_Posting_Date', 'Preference', 'Contact_Person', 'Contact',
       'Job_Title', 'Role', 'Job_Portal', 'Job_Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company_Profile'],
      dtype='object')

In [15]:
df.isnull().sum()

Job_Id                 0
Experience             0
Qualifications         0
Salary_Range           0
location               0
Country                0
latitude               0
longitude              0
Work_Type              0
Company_Size           0
Job_Posting_Date       0
Preference             0
Contact_Person         0
Contact                0
Job_Title              0
Role                   0
Job_Portal             0
Job_Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company_Profile     3607
dtype: int64

In [16]:
df.shape

(1048575, 23)

In [22]:
df.dropna(inplace=True)

/var/folders/ng/w1bnc_j103q6_zxdt64_splr0000gn/T/ipykernel_1685/1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [23]:
df.isnull().sum()

Job_Id              0
Experience          0
Qualifications      0
Salary_Range        0
location            0
Country             0
latitude            0
longitude           0
Work_Type           0
Company_Size        0
Job_Posting_Date    0
Preference          0
Contact_Person      0
Contact             0
Job_Title           0
Role                0
Job_Portal          0
Job_Description     0
Benefits            0
skills              0
Responsibilities    0
Company             0
Company_Profile     0
dtype: int64

In [21]:
df.drop_duplicates(inplace=True)

/var/folders/ng/w1bnc_j103q6_zxdt64_splr0000gn/T/ipykernel_1685/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [28]:
df.to_excel("/Users/sidhi/Desktop/cleaned_data.xlsx", index=False)